### ISSUE TITLE
semantic-release can't push to repo

### ISSUE THREAD

**Issue by rvagg** [nodejs/nodejs-dist-indexer#39]
Halp, I don't remember how to solve this issue since the thing was changed in the nodejs org: https://github.com/nodejs/nodejs-dist-indexer/actions/runs/11470886766/job/31920891266

> semantic-release cannot push the version tag to the branch main on the remote Git repository with URL https://x-access-token:[secure]@github.com/nodejs/nodejs-dist-indexer.git.

<img width="803" alt="Screenshot 2024-10-23 at 12 06 44 PM" src="https://github.com/user-attachments/assets/17373c11-e666-4ea0-8546-16380f6124f0">

@richardlau? Someone else? What was the magic password to make this work?

**Comment by richardlau** [comment]
I haven't had time to figure this out yet https://github.com/nodejs/nodejs-dist-indexer/issues/32. It may be as simple as 
```
permissions:
  contents: read # for checkout
```
https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#.github-workflows-release.yml-configuration-for-node-projects
or it may require a [new token](https://github.com/nodejs/admin/blob/main/request-an-access-token.md).

**Comment by richardlau** [comment]
oh if it's for writing tags to the repo, probably
```
    permissions:
      contents: write # to be able to publish a GitHub release
```
(also from https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#.github-workflows-release.yml-configuration-for-node-projects)?

**Comment by rvagg** [comment]
oh, that's right, now I remember we had to do that for the snap repo, thanks Richard!

**Comment by richardlau** [comment]
Fixed by https://github.com/nodejs/nodejs-dist-indexer/pull/40.
